// protoc -I./ ./routed_msg.proto --go_out=plugins=grpc:. --go_opt=module=github.com/yh742/j2735-decoder/pkg/routedmsgpb

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.10.0
// source: routed_msg.proto

package main

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  int32 `protobuf:"varint,1,opt,name=latitude,proto3" json:"latitude,omitempty"`   // in 1/10th microdegrees
	Longitude int32 `protobuf:"varint,2,opt,name=longitude,proto3" json:"longitude,omitempty"` // in 1/10th microdegrees
}

func (x *Position) Reset() {
	*x = Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_routed_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_routed_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_routed_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetLatitude() int32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Position) GetLongitude() int32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type RoutedMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgBytes                []byte               `protobuf:"bytes,1,opt,name=msgBytes,proto3" json:"msgBytes,omitempty"`
	Time                    *timestamp.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Position                *Position            `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	CustomRadius            int32                `protobuf:"varint,4,opt,name=customRadius,proto3" json:"customRadius,omitempty"` // only applies to some types of messages (not yet implemented)
	ClientCanOverrideRadius bool                 `protobuf:"varint,5,opt,name=clientCanOverrideRadius,proto3" json:"clientCanOverrideRadius,omitempty"`
}

func (x *RoutedMsg) Reset() {
	*x = RoutedMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_routed_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoutedMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutedMsg) ProtoMessage() {}

func (x *RoutedMsg) ProtoReflect() protoreflect.Message {
	mi := &file_routed_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutedMsg.ProtoReflect.Descriptor instead.
func (*RoutedMsg) Descriptor() ([]byte, []int) {
	return file_routed_msg_proto_rawDescGZIP(), []int{1}
}

func (x *RoutedMsg) GetMsgBytes() []byte {
	if x != nil {
		return x.MsgBytes
	}
	return nil
}

func (x *RoutedMsg) GetTime() *timestamp.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *RoutedMsg) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *RoutedMsg) GetCustomRadius() int32 {
	if x != nil {
		return x.CustomRadius
	}
	return 0
}

func (x *RoutedMsg) GetClientCanOverrideRadius() bool {
	if x != nil {
		return x.ClientCanOverrideRadius
	}
	return false
}

var File_routed_msg_proto protoreflect.FileDescriptor

var file_routed_msg_proto_rawDesc = []byte{
	0x0a, 0x10, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0b, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x64, 0x6d, 0x73, 0x67, 0x70, 0x62, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x44, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6c, 0x6f, 0x6e,
	0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0xe8, 0x01, 0x0a, 0x09, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x64, 0x4d, 0x73, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x42, 0x79, 0x74, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6d, 0x73, 0x67, 0x42, 0x79, 0x74, 0x65, 0x73,
	0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x12, 0x31, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x64, 0x6d, 0x73, 0x67, 0x70, 0x62,
	0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x52, 0x61, 0x64,
	0x69, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x12, 0x38, 0x0a, 0x17, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x43, 0x61, 0x6e, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x52, 0x61, 0x64, 0x69,
	0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x17, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x43, 0x61, 0x6e, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x52, 0x61, 0x64, 0x69, 0x75,
	0x73, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x79, 0x68, 0x37, 0x34, 0x32, 0x2f, 0x6a, 0x32, 0x37, 0x33, 0x35, 0x2d, 0x64, 0x65, 0x63, 0x6f,
	0x64, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x64, 0x6d, 0x73,
	0x67, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_routed_msg_proto_rawDescOnce sync.Once
	file_routed_msg_proto_rawDescData = file_routed_msg_proto_rawDesc
)

func file_routed_msg_proto_rawDescGZIP() []byte {
	file_routed_msg_proto_rawDescOnce.Do(func() {
		file_routed_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_routed_msg_proto_rawDescData)
	})
	return file_routed_msg_proto_rawDescData
}

var file_routed_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_routed_msg_proto_goTypes = []interface{}{
	(*Position)(nil),            // 0: routedmsgpb.Position
	(*RoutedMsg)(nil),           // 1: routedmsgpb.RoutedMsg
	(*timestamp.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_routed_msg_proto_depIdxs = []int32{
	2, // 0: routedmsgpb.RoutedMsg.time:type_name -> google.protobuf.Timestamp
	0, // 1: routedmsgpb.RoutedMsg.position:type_name -> routedmsgpb.Position
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_routed_msg_proto_init() }
func file_routed_msg_proto_init() {
	if File_routed_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_routed_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_routed_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoutedMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_routed_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_routed_msg_proto_goTypes,
		DependencyIndexes: file_routed_msg_proto_depIdxs,
		MessageInfos:      file_routed_msg_proto_msgTypes,
	}.Build()
	File_routed_msg_proto = out.File
	file_routed_msg_proto_rawDesc = nil
	file_routed_msg_proto_goTypes = nil
	file_routed_msg_proto_depIdxs = nil
}
